services:
  - type: web
    name: superres-server
    env: python
    buildCommand: |
      pip install -r requirements.txt
      bash download_models.sh
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: REAL_ESRGAN_MODEL_PATH
        value: "/opt/render/project/src/models/RealESRGAN_x4plus.pth"
      - key: SWINIR_ONNX_PATH
        value: "/opt/render/project/src/models/swinir_x4.onnx"
      - key: OPENCV_SR_MODEL_PATH
        value: "/opt/render/project/src/models/EDSR_x4.pb"
